In [114]:
import numpy as np
import math
pi=np.pi
def sin(t):
    return(round(np.sin(t/180*pi),9))
def cos(t):
    return(round(np.cos(t/180*pi),9))
def ten(t):
    return(round(np.tan(t/180*pi),9))
def atan2(x,y):
    return(round(np.arctan2(x,y)*180/pi,9))
def DH(i,a,alpha,d,theta):
    i-=1
    return(np.mat([[cos(theta[i]),-sin(theta[i]),0,a[i]],
                     [sin(theta[i])*cos(alpha[i]),cos(theta[i])*cos(alpha[i]),-sin(alpha[i]),-sin(alpha[i])*d[i]],
                     [sin(theta[i])*sin(alpha[i]),cos(theta[i])*sin(alpha[i]),cos(alpha[i]),cos(alpha[i])*d[i]],
                     [0,0,0,1]]))
def ivk(t,a,alpha,d):
    th11=round(atan2(t[1,3],t[0,3])-atan2(0,(t[0,3]**2 + t[1,3]**2)**0.5),2)
    th12=round(atan2(t[1,3],t[0,3])-atan2(0,-(t[0,3]**2 + t[1,3]**2)**0.5),2)
    k=(t[0,3]**2+t[1,3]**2+t[2,3]**2-a[2]**2-a[3]**2-d[2]**2-d[3]**2)/(2*a[2])
    th31=round(atan2(a[3],d[3])-atan2(k,((a[3]**2)+(d[3]**2)-(k**2))**0.5),2)
    th32=round(atan2(a[3],d[3])+atan2(k,-((a[3]**2)+(d[3]**2)-(k**2))**0.5),2)
    return(th11,th12,th31,th32)

In [115]:
# DH_Model
a_list = [0,0,150,30,0,0]
alpha =  [0,-90,0,-90,90,-90]
d_list = [0,0,0,100,0,0]
theta =  [20,90,20,90,-90,0]
t01=DH(1,a_list,alpha,d_list,theta)
t12=DH(2,a_list,alpha,d_list,theta)
t23=DH(3,a_list,alpha,d_list,theta)
t34=DH(4,a_list,alpha,d_list,theta)
t45=DH(5,a_list,alpha,d_list,theta)
t56=DH(6,a_list,alpha,d_list,theta)
t06=t01*t12*t23*t34*t45*t56
print(t06)
print(ivk(t06,a_list,alpha,d_list))

[[ 8.83022222e-01  3.21393805e-01  3.42020143e-01 -9.79440363e+01]
 [ 3.21393805e-01  1.16977778e-01 -9.39692621e-01 -3.56487138e+01]
 [-3.42020143e-01  9.39692621e-01  0.00000000e+00 -1.43988764e+02]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
(-160.0, -340.0, 20.0, -160.0)
