In [115]:
import numpy as np
import math
pi=np.pi
def sin(t):
    return(round(np.sin(t/180*pi),9))
def cos(t):
    return(round(np.cos(t/180*pi),9))
def tan(t):
    return(round(np.tan(t/180*pi),9))
def atan(x,y):
    return(round(np.arctan(y/x)*180/pi,9))
def atan2(y,x):
    return(round(np.arctan2(y,x)*180/pi,9))
def DH(i,a,alpha,d,theta):
    i-=1
    return(np.mat([[cos(theta[i]),-sin(theta[i]),0,a[i]],
                     [sin(theta[i])*cos(alpha[i]),cos(theta[i])*cos(alpha[i]),-sin(alpha[i]),-sin(alpha[i])*d[i]],
                     [sin(theta[i])*sin(alpha[i]),cos(theta[i])*sin(alpha[i]),cos(alpha[i]),cos(alpha[i])*d[i]],
                     [0,0,0,1]]))
def ivk(t,a,alpha,d):
    th11=round(atan2(t[1,3],t[0,3])+atan2(d[2],(t[0,3]**2 + t[1,3]**2-d[2]**2)**0.5),2)
    th12=round(atan2(t[1,3],t[0,3])-atan2(d[2],-(t[0,3]**2 + t[1,3]**2-d[2]**2)**0.5),2)
    k=(t[0,3]**2+t[1,3]**2+t[2,3]**2-a[2]**2-a[3]**2-d[2]**2-d[3]**2)/(2*a[2])
    th31=round(atan2(a[3],d[3])-atan2(k,((a[3]**2)+(d[3]**2)-(k**2))**0.5),2)
    th32=round(atan2(a[3],d[3])+atan2(k,-((a[3]**2)+(d[3]**2)-(k**2))**0.5),2)
    return(th11,th12,th31,th32)
def ivks(t,a,alpha,d):
    th11=round(atan(t[0,3],t[1,3])+atan((t[0,3]**2 + t[1,3]**2-d[2]**2)**0.5,d[2]),2)
    th12=round(atan(t[0,3],t[1,3])-atan(-(t[0,3]**2 + t[1,3]**2-d[2]**2)**0.5,d[2]),2)
    k=(t[0,3]**2+t[1,3]**2+t[2,3]**2-a[2]**2-a[3]**2-d[2]**2-d[3]**2)/(2*a[2])
    th31=round(atan(d[3],a[3])-atan(((a[3]**2)+(d[3]**2)-(k**2))**0.5,k),2)
    th32=round(atan(d[3],a[3])+atan(-((a[3]**2)+(d[3]**2)-(k**2))**0.5,k),2)
    
    return(th11,th12,th31,th32)

In [116]:
# DH_Model
a_list = [0,0,100,30,0,0]
alpha =  [0,-90,0,-90,90,-90]
d_list = [0,0,50,100,0,0]
theta =  [20,90,20,90,-90,0]
t01=DH(1,a_list,alpha,d_list,theta)
t12=DH(2,a_list,alpha,d_list,theta)
t23=DH(3,a_list,alpha,d_list,theta)
t34=DH(4,a_list,alpha,d_list,theta)
t45=DH(5,a_list,alpha,d_list,theta)
t56=DH(6,a_list,alpha,d_list,theta)
t06=t01*t12*t23*t34*t45*t56
print(t06)
print(ivk(t06,a_list,alpha,d_list))
th11,th12,th31,th32=ivk(t06,a_list,alpha,d_list)
print(ivks(t06,a_list,alpha,d_list))

[[   0.88302222    0.3213938     0.34202014 -115.04504348]
 [   0.3213938     0.11697778   -0.93969262   11.33591724]
 [  -0.34202014    0.93969262    0.          -93.98876433]
 [   0.            0.            0.            1.        ]]
(200.0, 20.0, 20.0, -160.0)
(20.0, 20.0, 20.0, 20.0)


In [117]:
a=a_list
d=d_list
t=t06
for th1 in [th11,th12]:
    for th3 in [th31,th32]:
        th23=atan2((-d[3]+a[2]*sin(th3))*t[2,3]-(a[3]+a[2]*cos(th3))*(t[0,3]*cos(th1)+t[1,3]*sin(th1)),
                   (-a[3]-a[2]*cos(th3))*t[2,3]-(d[3]-a[2]*sin(th3))*(t[0,3]*cos(th1)+t[1,3]*sin(th1)))
        print(th1,th3)
        print((-d[3]+a[2]*sin(th3))*t[2,3]-(a[3]+a[2]*cos(th3))*(t[0,3]*cos(th1)+t[1,3]*sin(th1)),
              (-a[3]-a[2]*cos(th3))*t[2,3]-(d[3]-a[2]*sin(th3))*(t[0,3]*cos(th1)+t[1,3]*sin(th1)))
        print(th23)
        print('--------------')

200.0 20.0
-6737.028256124416 4793.602500207121
-54.566980832
--------------
200.0 -160.0
19280.989137601297 -20000.249922150848
136.048999563
--------------
20.0 20.0
19105.570998816434 18509.833019154677
45.90735217
--------------
20.0 -160.0
5945.973851706683 7975.466122389047
36.705747445
--------------


In [118]:
print(sin(0),sin(180),cos(0),cos(180))

0.0 0.0 1.0 -1.0
